### ISSUE TITLE
TypeError: 'DataArrayCoordinates' object is not callable

### ISSUE THREAD

**Issue by ssdewangkaiyang** [tobac-project/tobac-tutorials#9] opened 2022-02-20 11:56 UTC
Hi, hello, when I run the first program, in the 

 `dxy,dt=tobac.utils.get_spacings(OLR)`

 section, pycharm reports an error! The error content is as follows: 

`  File "D:\DCC\DCCV02\Tobac\Tracking of deep convection.py", line 63, in <module>
    dxy,dt=tobac.utils.get_spacings(OLR)
  File "D:\Anaconda\envs\DCCV02\lib\site-packages\tobac\utils.py", line 427, in get_spacings
    coord_names=[coord.name() for coord in  field_in.coords()]
TypeError: 'DataArrayCoordinates' object is not callable
`
I'm a newbie and I've tried to find a way to solve this problem on the net, but can't find a way. Please help if you see it, Thanks!

**Comment by w-k-jones** [comment] 2022-02-21 16:10
Hi! Could you let us know which version of tobac you are using? The tutorials are currently being updated for a different build, so some versions might not be compatible

**Comment by JuliaKukulies** [comment] 2022-04-06 22:22
This issue is for sure caused by the version of tobac @ssdewangkaiyang, because ```get_spacings``` does only work with xarrays if you use a newer tobac version (where the xarray object is internally converted to an iris cube). Please follow the [instructions](https://github.com/climate-processes/tobac-tutorials/blob/master/docs/RunningTutorials.md) and use the notebooks together with the ```v2.0-dev``` branch

**Comment by fsenf** [comment] 2022-06-29 08:48
I have the feeling that the version aspect is rather clearly described in our README, now. I will close this issue ...

**Closed as completed by fsenf** 2022-06-29 08:48 UTC
