### ISSUE TITLE
Setup ReadTheDocs Rendering

### ISSUE THREAD

**Issue by fsenf** [tobac-project/tobac-tutorials#16] opened 2022-06-23 14:29 UTC
I realized that RTD rendering have not been setup so far for the tutorial notebooks.

Next steps:

- [x] setup rtd connection
- [x] update .readthedoc configuration: it currently uses python3.7 and build process fails with a 'jinja2' error
- [x] check how rendering looks like
- [x] update readme and provide a link to RTD

**Comment by fsenf** [comment] 2022-06-23 14:31
This is the currently build error

```bash
/home/docs/checkouts/readthedocs.org/user_builds/tobac-tutorials/envs/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tobac-tutorials/envs/latest/lib/python3.7/site-packages/sphinx/__main__.py", line 13, in <module>
    from sphinx.cmd.build import main
  File "/home/docs/checkouts/readthedocs.org/user_builds/tobac-tutorials/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/docs/checkouts/readthedocs.org/user_builds/tobac-tutorials/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/home/docs/checkouts/readthedocs.org/user_builds/tobac-tutorials/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/home/docs/checkouts/readthedocs.org/user_builds/tobac-tutorials/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/home/docs/checkouts/readthedocs.org/user_builds/tobac-tutorials/envs/latest/lib/python3.7/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/tobac-tutorials/envs/latest/lib/python3.7/site-packages/jinja2/__init__.py)

```

**Comment by freemansw1** [comment] 2022-07-05 20:14
It seems like the issue is related to this issue raised on the RTD page: https://github.com/readthedocs/readthedocs.org/issues/9038 . I think there are two solutions: first to set `jinja2<3.1.0` as a requirement or update the python version in `requirements.txt`.

**Comment by fsenf** [comment] 2022-08-19 13:31
As it looks today, RTD rendering works well. No active change in our config was done. I guess a bug was fixed on RTD side ... time heals

So, remaining task is updating the links to this nice page: https://tobac-tutorials.readthedocs.io/en/latest/

**Comment by lettlini** [comment] 2023-04-13 08:11
This has been completed with https://github.com/tobac-project/tobac-tutorials/pull/30. I think we can therefore close this issue.

**Closed as completed** 2023-05-24 12:46 UTC
